### ISSUE TITLE
תקיעה בתחילת המשחק

### ISSUE THREAD

**Issue by itamarc101** [Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony#1]
כשהתחלתי את המשחק היתה את הדמות הכחולה שכביכול רשום follow me 
אבל משום מה זה נתקע והיא לא זזה גם אחרי שזזתי
אבל אחרי איזה חצי דקה או דקה היא התחילה לזוז

**Comment by ofekrotem** [comment]
Can't recreate
