### ISSUE TITLE
השקופיות של הטקסט

### ISSUE THREAD

**Issue by hodwys** [Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony#10]
לא לכל שקופית יש את אותו אורך מלל אך יש את אותו בזמן לכולם אז יש כאלה שסיממתי לקרוא מזמן ויש כאלה שלא הצלחתי לקרוא בזמן. וגם הרגיש לי יותר מדי מלל שאני לא יודעת מתי הוא נגמר

**Comment by ofekrotem** [comment]
fixed
