### ISSUE TITLE
טקסט במהלך המשחק

### ISSUE THREAD

**Issue by HadarBitan** [Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony#11]
הטקסט במהלך המשחק נבלע בעצמים אם נמצאים יותר מדי קרוב ואז לא רואים את הטקסט צריך להתרחק מהעצם על מנת לראות את הטקסט.

![image](https://github.com/Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony/assets/86705118/ce362185-bd20-41f6-869b-d9d80c9a8200)

**Comment by ofekrotem** [comment]
fixed
