### ISSUE TITLE
באג במשחק הסצנה הראשונה במכות מול צוקו

### ISSUE THREAD

**Issue by Michael-Aga** [Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony#12]
![image](https://github.com/Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony/assets/85742675/435ebd4b-62d8-40c1-bde6-81c81a1314f0)
הגעתי למצב שפשוט אפשר להפוך את השחקנים והמשחק לא מתקדם לשום מקום וגם אפשר לצאת מהמשחק ולעוף לשמיים ולא רואים את השחקן בשמיים

**Comment by ofekrotem** [comment]
fixed
