### ISSUE TITLE
review

### ISSUE THREAD

**Issue by sagir567** [Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony#13]
1) can't speed up the text, to long text...
2) to hard to read the text inside the game, the colors of the map are stronger than the text color 
3) dialogue continues even when the player is far from the NPC, which a bit problem
4) jumping doesn't smooth, and bunnyhop style(keep jumping in the air) makes you fly, also the player rotates in the air... 
5) redundant multiple training, why so many training levels to tell me to press another button, this was understandable in the introduction 
6) no story or explanation of the purpose of the game

**Comment by ofekrotem** [comment]
fixed
