### ISSUE TITLE
זמן ההצגה של המלל טקסט

### ISSUE THREAD

**Issue by liron02319** [Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony#14]
אהבתי תמוזיקה ותאווירה של הטקסט וכו' אבל זמן ההצגה קצת ארוך מידי והיה נחמד אם היה אולי SPACE כדי להמשיך במקום לחכות שהזמן של הטקסט יעבור לטקסט הבא

**Comment by ofekrotem** [comment]
fixed
