### ISSUE TITLE
תנועה

### ISSUE THREAD

**Issue by Dorshir** [Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony#15]
במפה עצמה, לא ברור איפה אפשר ללכת ואיפה לא.
יש tiles שאתה מבין שאי אפשר לעמוד עליהם, אבל יש מקומות שאכן ניתן לעמוד על אותו tiles, מה שגורם לשחקן לא להיות בטוח היכן הוא יכול לעבור והיכן לא, פשוט חיפשתי קובייה קובייה איפה אפשר ואיפה לא...
חוץ מזה, בתוך המחנה אימונים, אי אפשר ללחוץ רצוף ימינה ושמאלה ולהתקדם בהמשכיות כמו מחוץ למחנה האימונים. אין אחידות.

**Comment by ofekrotem** [comment]
fixed
