### ISSUE TITLE
הקרב בארנה

### ISSUE THREAD

**Issue by EdenRoas** [Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony#16]
הקרב בארנה - כשאנג נפגע או מתהפך הוא נשאר באותה צורה גם אם הלחימה נמשכת.
![image](https://github.com/Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony/assets/92533182/f4b66e91-598a-4477-b702-09d8e05fe64a)

**Comment by ofekrotem** [comment]
fixed
