### ISSUE TITLE
review

### ISSUE THREAD

**Issue by Noya-G** [Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony#17]
<img width="1680" alt="Screenshot 2024-03-06 at 14 39 33" src="https://github.com/Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony/assets/73538626/8e083adc-7d35-47ff-b0f7-26c0858508e0">
<img width="1680" alt="Screenshot 2024-03-06 at 14 41 30" src="https://github.com/Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony/assets/73538626/118a5e67-f1c8-4103-8a87-0748cebc6382">

I have came to an issue that when I jump and land on another player, two of them fall on the side and didn't came back to there regular position.

It want clear that I need to end the tutorial to stat the game.

**Comment by ofekrotem** [comment]
fixed
