### ISSUE TITLE
לא ברור מה ההבדל בין כל ההתקפות

### ISSUE THREAD

**Issue by erelsgl** [Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony#20]
השחקן לומד 4 התקפות שונות, אבל כולן עושות אותו הדבר - רק הגרפיקה שונה. צריך שיהיה הבדל בין ההתקפות. לדוגמה: 
* אויר - מעיף את היריב אחורה עד שהוא יוצא מהמסך ונופל; 
* מים - מטביע את היריב - לא מוריד חיים עד שכל האיזור מלא במים ואז היריב טובע;
* אש - התקפה רגילה - מוריד חיים;
* אדמה - גוש אדמה כבד, משתק את היריב כך שהוא לא יכול לזוז.
אפשר גם לחשוב על הבדלים אחרים, החשוב הוא שתהיה סיבה לשחקן להשתמש בכל ההתקפות - לא רק בהתקפה אקראית כלשהי.

**Comment by ofekrotem** [comment]
took inspiration and added something similar :)
