### ISSUE TITLE
האויב זז למרות שהקרב עוד לא התחיל

### ISSUE THREAD

**Issue by erelsgl** [Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony#21]
בכל קרב, יש הסברים בהתחלה, אבל האויב והשחקן כבר יכולים לזוז.
לכן השחקן חושב שהמשחק התחיל, ומתחיל לירות - אבל כל עוד יש הסברים, לא יורדים חיים. זה מבלבל.
צריך שיהיה ברור לשחקן, שהקרב עדיין לא התחיל. לדוגמה, אפשר בהתחלה לשים קיר בין השחקן ליריב, ולהעלים את הקיר רק אחרי שהטקסט נגמר.

**Comment by ofekrotem** [comment]
added explanation
