### ISSUE TITLE
בשלב של הקרב נגד אנשים אחרים

### ISSUE THREAD

**Issue by itamarc101** [Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony#3]
בשלב הזה כן הצלחתי לתקוף
משהו שאםשר לתקן - צריך בהליכה לעשות שאפשר ללחוץ רצוף על המקשים
הייתי צריך ללחות הרבה פעמים על המקש כדי לזוז
שמתי לב לעוד משהו שהדמות שלי התהפכה הפוך אני אצרף תמונה
עוד משהו - אי אפשר להתסובב לצד השני כלומר אם החלפתי מיקום עם האויב אני לא יכול לתקוף שמאלה

בנוסף אפשר לקפוץ הרבה פעמים גם מהאוויר גם מחוץ למסך (לא יודע אם זאת היתה הכוונה של המפתחים)
![WhatsApp Image 2024-03-06 at 08 43 09](https://github.com/Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony/assets/45041126/af893d30-59c3-47d8-a9b2-1399346d098a)
![WhatsApp Image 2024-03-06 at 08 41 53](https://github.com/Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony/assets/45041126/a3c83c0a-3446-4d77-8eb9-1e2318f0650c)

**Comment by ofekrotem** [comment]
fixed
