### ISSUE TITLE
נתקעתי בקרב נגד צוקו באימון אש

### ISSUE THREAD

**Issue by Maor-Or** [Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony#5]
לא נתן לי  להוריד לצוקו את החיים, ולא נתן לצוקו להוריד לי את החיים, אז לא יכלתי לצאת מהקרב

**Comment by Maor-Or** [comment]
בנוסף יכלתי לדחוף את דמות האויב בכך שאני זז עליו

**Comment by ofekrotem** [comment]
הסברים הובהרו
