### ISSUE TITLE
לא כתוב איך תוקפים + נתקעים באימון האש  למרות שניצחתי 

### ISSUE THREAD

**Issue by ohadtaizi** [Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony#6]
למרות שאני מנצח את היריב אני חוזר על אותה משימה שוב ושוב .
לא כתוב בהסבר איך משתמשים במתקפה .
כאשני קופץ אני לא נוחת על הרגליים

**Comment by ofekrotem** [comment]
fixed
