### ISSUE TITLE
אפשרות להריץ את הפתיח

### ISSUE THREAD

**Issue by AdiNahmias** [Mishakim-Lamahshev/Avatar-Shadows-Of-Harmony#9]
נכנסתי לשחק במשחק שוב ולא רציתי לקרוא שוב את כל הפתיח..
אולי שתהיה אפשרות לדלג על כל עמוד כזה בזמן המתאים לך, כך שגם מי שקורא לאט יוכל לקרוא הקצב שלו.

**Comment by ofekrotem** [comment]
added
